version: '3'

services:
  website:
    image: website
    build: 
      context: .
      dockerfile: DockerfileWeb
    environment:
      NODE_EN: =production
      GRAPHQL_URL: http://192.168.99.100:63002/graphql
    ports:
      - 63001:80

  api:
    image: nodegraphqlserver
    build: 
      context: .
      dockerfile: DockerfileApi
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://sydney:900@mongodb:27017/sydney900
    ports:
      - 63002:80
    depends_on:
      - mongodb      

  mongodb:
    image: mymongodb
    build: 
      context: .
      dockerfile: DockerfileDb
    environment:
          - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodata:/data/configdb 
      - mongodata:/data/db 
    ports:
      - 27017:27017

volumes:
  mongodata:      