version: '2.1'

services:
  node-graphql-server-and-react-client:
    image: node-graphql-server-and-react-client
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 63001:63001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js