version: '3'

services:
  api:
    image: nodegraphqlserver
    build: 
      context: .
      dockerfile: DockerfileApi
    environment:
      NODE_ENV: production
    ports:
      - 63002:63002
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js